$(document).ready(function(){
	$('.activityContainer').fadeIn();

	$('.response').mouseenter(function(){
		$(this).addClass('over');
	})
	$('.response').mouseleave(function(){
		$('.response').removeClass('over');
	})
	$('.response').on('click',function(){
		console.log($(this).attr('data-index'))
		if(!$(this).hasClass('disabled'))
		{
			if($(this).attr('data-index')=='2'||$(this).attr('data-index')=='3'){
				$(this).addClass('correct');
			}
			else{
				$('.response').eq(2).addClass('correct');
				$(this).addClass('incorrect');
			}
		}
		$('.feedback-holder').show();
		$('.response').addClass('disabled');
		complete_page();
		enableNextBtn();
	})
})